bunks/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'bunks'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('<str:username>/', views.UserFeedView.as_view(), name='user_feed'),
    path('<str:username>/bunk', views.bunk, name='bunk')
]

jitterbunk/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bunks/', include('bunks.urls'))
]

bunks/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
    username = models.CharField(max_length=100)
    photo = models.CharField(max_length=500)

    def __str__(self):      
        return self.username

class Bunk(models.Model):
    from_user = models.ForeignKey(User, related_name="bunks_out", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="bunks_in", on_delete=models.CASCADE)
    time = models.TimeField(default=timezone.now)
    
    def __str__(self):
        return ("from " + str(self.from_user) + " to " + str(self.to_user))

bunks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import User, Bunk
# Create your views here.

class FeedView(generic.ListView):
    template_name = 'bunks/feed.html'
    context_object_name = 'bunk_list'
    model = Bunk

    # def get_context_data(self, **kwargs):
    #     """Add to context, Return dictionary."""
    #     context = super(FeedView, self).get_context_data(**kwargs)
    #     context['']

class UserFeedView(generic.ListView):
    template_name = 'bunks/user_feed.html'
    context_object_name = 'bunk_list'
    
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Bunk.objects.filter(
            to_user=get_object_or_404(User, username=self.kwargs['username']).id
        )

    def get_context_data(self, **kwargs):
        context = super(UserFeedView, self).get_context_data(**kwargs)
        context['kwargs']=self.kwargs
        return context

def bunk(request, username):
    to_username = request.POST['to_user']
    try:
        from_user=User.objects.get(username=username)
        to_user=User.objects.get(username=to_username)
        bunk = Bunk(from_user=from_user, to_user=to_user)
    except (KeyError, User.DoesNotExist):
        #Not sure if this is the best approach, seems to be somewhat wasteful when we are already on the user's page
        return render(request, 'bunks/user_feed.html', {
            'bunk_list': from_user.bunks_in.all(),
            'error_message': to_username+ " not found.",
            'user': request.POST['to_user'],
            'kwargs': {'username': username}
        })
    else:
        bunk.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('bunks:user_feed', args=(to_user.username,)))

bunks/templates/bunks/feed.html
<style>
    .container {
        display: flex;
        height: 300px;
        width: 300px; 
        margin-bottom: 20px;
    }
    img {
        width: 100%;
        max-height: 100%;
        border-radius: 25px;
    }
    .row {
        display: flex;
        width: 100%;
        flex-direction: row;
        align-items: center;
        justify-content: space-around;
    }
    .col {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    h1 {
        text-align: center;
    }
</style>

{% if bunk_list %}
<h1>All Bunks!</h1>
    {% for bunk in bunk_list %}
        <div class="row">
            <div class="col">
                {{bunk.from_user.username}}
                <a href="{{bunk.from_user.username}}">
                    <div class="container">
                        <img src="{{bunk.from_user.photo}}" alt="photo"></img>
                    </div>
                </a>
            </div>
            <div class="col">
                <p>{{bunk.time}}</p>
                <p>--------></p>
            </div>
            <div class="col">
                {{bunk.to_user.username}}
                <a href="{{bunk.to_user.username}}">
                    <div class="container">
                        <img src="{{bunk.to_user.photo}}" alt="photo"></img>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <p>Nobody's bunked yet!</p>
{% endif %}

bunks/templates/bunks/user_feed.html
<style>
    .container {
        display: flex;
        height: 300px;
        width: 300px; 
        margin-bottom: 20px;
    }
    img {
        width: 100%;
        max-height: 100%;
        border-radius: 25px;
    }
    .row {
        display: flex;
        width: 100%;
        flex-direction: row;
        align-items: center;
        justify-content: space-around;
    }
    .col {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    h1 {
        text-align: center;
    }
    h2 {
        text-align: center;
    }
</style>

{% if bunk_list %}
<h1>{{kwargs.username}}'s Bunks!</h1>
<a href="../"><h2>Full Feed</h2></a>
<div class="col">
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for bunk in bunk_list %}
        <div class="row">
            <div class="col">
                {{bunk.from_user.username}}
                <a href="../{{bunk.from_user.username}}">
                    <div class="container">
                        <img src="{{bunk.from_user.photo}}" alt="photo"></img>
                    </div>
                </a>
            </div>
            <div class="col">
                <p>{{bunk.time}}</p>
                <p>--------></p>
            </div>
            <div class="col">
                {{bunk.to_user.username}}
                    <div class="container">
                        <img src="{{bunk.to_user.photo}}" alt="photo"></img>
                    </div>
            </div>
        </div>
    {% endfor %}
<form action="{% url 'bunks:bunk' kwargs.username %}" method="post">
    {% csrf_token %}
    <input type="text" name="to_user" id="to_user">
        <label for="to_user">Who do you want to bunk?</label><br>
    <input type="submit" value="Bunk">
</form>
</div>
{% else %}
    <p>Nobody's bunked yet!</p>
{% endif %}